[api]
model="gpt-3.5-turbo"
api_key="xxx"
base_url="https://api.openai.com/v1"

[prompts]
[prompts.to-ch]
description = "Translate the text into Chinese"
prefix = "Please translate the following text into Chinese: \n\n"

[prompts.to-en]
description = "Translate the text into English"
prefix = "Please translate the following text into English: \n\n"

[prompts.edit]
description = "Edit the text to make it more natural"
prefix = "Please edit the following text to make it more natural: \n\n"

[prompts.commit]
description = "Modify the commit message to make it more compliant with commit message specifications"
prefix = "The following is a git repository commit message. Help me modify it to make it more compliant with commit message specifications: \n\n"